[Generic]
  mode = "tray"
  auto_start = false
  max_processes = 20
  web_server_port = 8080
  log_rotation_days = 7
  local_ui_type = "react"
  show_console_on_startup = true

[Paths]
  podman_exe = "c:/Program Files/RedHat/Podman/podman.exe"
  tshark_exe = "c:/Program Files/Wireshark/tshark.exe"
  filter_list = "settings/generic.flt"
  control_list = "settings/generic.ctr"
  alerts_list = "settings/generic.alr"
  db_image = "progs/cachedb/dragonflydb.tar.gz"
  db_backup_dir = "cache"

[DragonflyDB]
  host = "127.0.0.1"
  port = 6379
  password = ""
  batch_size = 1000
  timeout = "5s"

[PostgreSQL]
  host = "127.0.0.1"
  port = 5432
  user = "postgres"
  password = "postgres"
  database = "Venera"
  ssl_mode = "disable"

[System]
  disk_warning_threshold = 15.0
  disk_critical_threshold = 5.0
  ram_critical_threshold = 5.0
